version: "3.9"
services:
  db:
    image: postgres:13
    shm_size: 512M
    ports:
     - '5432:5432'
    restart: always
    volumes:
     - db-data:/home/data  
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=dataregi
     - PGDATA=/home/data
volumes:
  db-data: