[default]
template_dir = "templates"
token_lifespan_minutes = 10
secret_key = "Y7JlcWBdCOhknIxnMkFlhtU7+tPF/V1x4X6vAzFqtCs="

[debug]
callback_name = "local"

[release]
callback_name = "www"

[default.tls]
certs = "dataregi.com/fullchain.pem"
key = "dataregi.com/privkey.pem"

[global.databases]
postgres_main={ url="postgres://postgres:postgres@localhost/dataregi"}