[default]
template_dir = "templates"

token_lifespan_minutes = 10
max_tries_minutes = 5

secret_key = "Y7JlcWBdCOhknIxnMkFlhtU7+tPF/V1x4X6vAzFqtCs="

aws_region = ["eu-west-1",]
aws_queue = "https://sqs.eu-west-1.amazonaws.com/334979221948/dataregi-emails-queue"


[limits]
file= "10Mib"

[debug]
callback_name = "local"

[release]
callback_name = "www"
address = "0.0.0.0"
port = 443

[default.tls]
certs = "dataregi.com/fullchain.pem"
key = "dataregi.com/privkey.pem"

[test]
secret_key = "34z7q9pR16SqrMFTptf7nte7iCpY/9S+TQYDVIwRNkA="
callback_name = "test"

#[default.databases]
#postgres_main={ url="postgres://postgres:postgres@localhost/dataregi"}

#[test.databases]
#postgres_main={ url="postgres://postgres:postgres@localhost/dataregi_test"}